export const port=3000;
export const mongoUrl="mongodb+srv://paanagalavijaykumar:zxcvbnmasdfghjkl@cluster0.nlbm7.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
const token ="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzY2MjRlYmNiODYzMzFmMjM5N2E4MDYiLCJpYXQiOjE3MzQ3NDczNzIsImV4cCI6MTczNzMzOTM3Mn0.94GJtrm3uwfBpWFn21ObLjGOfAdzDSHPJCC1WlEaBQk"